--connect DEV/PASSWORD

-- ILC Database Setup
-- Upgrades ILC schema to version 1.1

define ILC_SCHEMA=ILC;

ALTER TABLE &ILC_SCHEMA .SERVICE_INFO
MODIFY(USERID  NULL);

ALTER TABLE &ILC_SCHEMA .SERVICE_INFO
MODIFY(PWD  NULL);

ALTER TABLE &ILC_SCHEMA .IVR_SERVER
 ADD (DB_CONN  VARCHAR2(2000 BYTE));

ALTER TABLE &ILC_SCHEMA .IVR_SERVER
 ADD (ENABLED  NUMBER(1)                            DEFAULT 1                     NOT NULL);

ALTER TABLE &ILC_SCHEMA .IVR_PROJECT
 ADD (ENABLED  NUMBER(1)                            DEFAULT 1                     NOT NULL);

ALTER TABLE &ILC_SCHEMA .SERVICE_INFO
 ADD (ENABLED  NUMBER(1)                            DEFAULT 1                     NOT NULL);

CREATE OR REPLACE PROCEDURE &ILC_SCHEMA .INITIALIZE_CHECKLIST(
		TIME_SPAN IN NUMBER, 
		WAS_MISFIRED IN NUMBER, 
		A_REPORT_ID OUT NUMBER,
		A_START_TIME OUT DATE,
		PREV_START_TIME OUT DATE,
		IS_NEW_SESSION OUT NUMBER) AS
BEGIN
	IS_NEW_SESSION := 0;
	SELECT REPORT_ID, START_TIME INTO A_REPORT_ID, A_START_TIME 
		FROM &ILC_SCHEMA .SERVICE_VERIFICATION_SESSION FOR UPDATE;
	IF A_START_TIME < SYSDATE - TIME_SPAN THEN
		IS_NEW_SESSION := 1;
		PREV_START_TIME := A_START_TIME;
		SELECT &ILC_SCHEMA .SQ_SERVICE_VERIFICATION.NEXTVAL INTO A_REPORT_ID FROM DUAL;
		SELECT SYSDATE INTO A_START_TIME FROM DUAL;
		IF WAS_MISFIRED = 0 THEN
			INSERT INTO &ILC_SCHEMA .SERVICE_VERIFICATION(ITEM_ID, REPORT_ID, ATTEMPTS, STATUS, TIME)
				(SELECT ITEM_ID, &ILC_SCHEMA .SQ_SERVICE_VERIFICATION.CURRVAL, 0, 'AWAITING', A_START_TIME FROM &ILC_SCHEMA .SERVICE_INFO
					INNER JOIN &ILC_SCHEMA .IVR_PROJECT ON SERVICE_INFO.IVR_PROJECT_ID = IVR_PROJECT.IVR_PROJECT_ID AND IVR_PROJECT.ENABLED != 0
					INNER JOIN &ILC_SCHEMA .IVR_SERVER ON IVR_PROJECT.IVR_SERVER_ID = IVR_SERVER.IVR_SERVER_ID AND IVR_SERVER.ENABLED != 0
					WHERE SERVICE_INFO.ENABLED != 0
				);
			UPDATE &ILC_SCHEMA .SERVICE_VERIFICATION_SESSION 
				SET REPORT_ID = &ILC_SCHEMA .SQ_SERVICE_VERIFICATION.CURRVAL, START_TIME = A_START_TIME, IS_REPORTED=0;
		ELSE
			UPDATE &ILC_SCHEMA .SERVICE_VERIFICATION_SESSION 
				SET REPORT_ID = &ILC_SCHEMA .SQ_SERVICE_VERIFICATION.CURRVAL, START_TIME = A_START_TIME, IS_REPORTED=1;
		END IF;
	END IF;
	COMMIT;
END INITIALIZE_CHECKLIST;
/
